const db = require('./db');

async function fixOracleCache() {
  const tables = [
    { table: 'Book', col: 'book_id' },
    { table: 'Category', col: 'category_id' },
    { table: 'Author', col: 'author_id' },
    { table: 'Book_Copy', col: 'copy_id' },
    { table: 'Member', col: 'member_id' },
    { table: 'Librarian', col: 'librarian_id' },
    { table: 'Issue_Record', col: 'issue_id' },
    { table: 'Fine', col: 'fine_id' }
  ];

  const conn = await db.getConnection();
  try {
    for (const t of tables) {
      const sql = `ALTER TABLE ${t.table} MODIFY ${t.col} GENERATED BY DEFAULT AS IDENTITY NOCACHE`;
      try {
        await conn.execute(sql);
        console.log(`Updated ${t.table} to NOCACHE`);
      } catch (err) {
        console.error(`Failed to update ${t.table}:`, err.message);
      }
    }
  } catch (err) {
    console.error('Connection error:', err);
  } finally {
    await conn.close();
  }
}

fixOracleCache();
