-- Oracle schema for DBMS-focused Library Management System
-- Run this in SQL*Plus as the target user/schema.

-- Drop tables in reverse dependency order
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Fine CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Issue_Record CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Book_Copy CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Book_Author CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Author CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Book CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Category CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Member CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Librarian CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Category
CREATE TABLE Category (
  category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR2(100) NOT NULL UNIQUE
);

-- Book
CREATE TABLE Book (
  book_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            VARCHAR2(255) NOT NULL,
  isbn             VARCHAR2(20)  NOT NULL UNIQUE,
  publisher        VARCHAR2(150),
  publication_year NUMBER,
  category_id      NUMBER,
  CONSTRAINT fk_book_category
    FOREIGN KEY (category_id) REFERENCES Category (category_id),
  CONSTRAINT chk_publication_year
  CHECK (publication_year IS NULL OR publication_year >= 1500)
);

CREATE INDEX idx_book_title ON Book (title);

-- Author
CREATE TABLE Author (
  author_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(150) NOT NULL,
  nationality VARCHAR2(100)
);

CREATE INDEX idx_author_name ON Author (name);

-- Junction table Book_Author (many-to-many)
CREATE TABLE Book_Author (
  book_id   NUMBER NOT NULL,
  author_id NUMBER NOT NULL,
  CONSTRAINT pk_book_author PRIMARY KEY (book_id, author_id),
  CONSTRAINT fk_ba_book
    FOREIGN KEY (book_id) REFERENCES Book (book_id),
  CONSTRAINT fk_ba_author
    FOREIGN KEY (author_id) REFERENCES Author (author_id)
);

-- Book_Copy (each physical copy)
CREATE TABLE Book_Copy (
  copy_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id        NUMBER NOT NULL,
  status         VARCHAR2(20) DEFAULT 'available',
  shelf_location VARCHAR2(50),
  CONSTRAINT fk_copy_book
    FOREIGN KEY (book_id) REFERENCES Book (book_id),
  CONSTRAINT chk_copy_status
    CHECK (status IN ('available', 'issued', 'lost', 'maintenance'))
);

CREATE INDEX idx_copy_book_status ON Book_Copy (book_id, status);

-- Member
CREATE TABLE Member (
  member_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR2(150) NOT NULL,
  email           VARCHAR2(150) NOT NULL UNIQUE,
  phone           VARCHAR2(20),
  membership_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  status          VARCHAR2(20) DEFAULT 'active',
  CONSTRAINT chk_member_status
    CHECK (status IN ('active', 'inactive', 'banned'))
);

-- Librarian
CREATE TABLE Librarian (
  librarian_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(150) NOT NULL,
  email        VARCHAR2(150) NOT NULL UNIQUE
);

-- Issue_Record
CREATE TABLE Issue_Record (
  issue_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  copy_id     NUMBER NOT NULL,
  member_id   NUMBER NOT NULL,
  issue_date  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  due_date    DATE NOT NULL,
  return_date DATE,
  issued_by   NUMBER NOT NULL,
  CONSTRAINT fk_issue_copy
    FOREIGN KEY (copy_id) REFERENCES Book_Copy (copy_id),
  CONSTRAINT fk_issue_member
    FOREIGN KEY (member_id) REFERENCES Member (member_id),
  CONSTRAINT fk_issue_librarian
    FOREIGN KEY (issued_by) REFERENCES Librarian (librarian_id),
  CONSTRAINT chk_due_after_issue
    CHECK (due_date > issue_date)
);

CREATE INDEX idx_issue_member ON Issue_Record (member_id);
CREATE INDEX idx_issue_due ON Issue_Record (due_date);

-- Fine (one-to-one with Issue_Record)
CREATE TABLE Fine (
  fine_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id    NUMBER NOT NULL UNIQUE,
  amount      NUMBER(10, 2) NOT NULL,
  paid_status VARCHAR2(10) DEFAULT 'unpaid',
  CONSTRAINT fk_fine_issue
    FOREIGN KEY (issue_id) REFERENCES Issue_Record (issue_id),
  CONSTRAINT chk_fine_non_negative
    CHECK (amount >= 0),
  CONSTRAINT chk_fine_status
    CHECK (paid_status IN ('unpaid', 'paid'))
);
COMMIT;
